### ISSUE TITLE
MOD冲突

### ISSUE THREAD

**Issue by 623667595** [CleanroomMC/Fugue#1]
[错误报告-2024-1-13_22.58.14.zip](https://github.com/CleanroomMC/Fugue/files/13928497/-2024-1-13_22.58.14.zip)

**Comment by kappa-maintainer** [comment]
renderlib系列不打算兼容

**Comment by 623667595** [comment]
好像删了 也有冲突

**Comment by kappa-maintainer** [comment]
那就是别的冲突，去Discord聊

**Comment by 623667595** [comment]
[错误报告-2024-1-13_23.06.42.zip](https://github.com/CleanroomMC/Fugue/files/13928532/-2024-1-13_23.06.42.zip)

**Comment by 623667595** [comment]
> 那就是别的冲突，去Discord聊
有QQ或者VX吗

**Comment by 623667595** [comment]
> 那就是别的冲突，去Discord聊

我的网络用不了Discord

**Comment by 623667595** [comment]
已测试和Quick Easy Menu 冲突
