### ISSUE TITLE
It seems that `Charset` needs additional fix

### ISSUE THREAD

**Issue by ZZZank** [CleanroomMC/Fugue#12]
When Charset is installed, the game will crash on rendering Charset item/blocks in JEI. 
[crash-2024-01-27_23.05.06-client.txt](https://github.com/CleanroomMC/Fugue/files/14072757/crash-2024-01-27_23.05.06-client.txt)

I can reproduce this with only:
- Cleanroom 3028 (https://github.com/CleanroomMC/Cleanroom/actions/runs/7663947163)
- Fugue 0.5.2
- Charset-Lib 0.5.6.6
- Charset-StorageChests 0.5.6.6
- JEI 1.12.2-4.16.1.1003 (or HEI 0.25.1, the results are the same)

A simple way to reproduce this is to type `@charset` in JEI search

**Comment by kappa-maintainer** [comment]
I guess my Mixin gone wrong, checking

**Comment by kappa-maintainer** [comment]
Try this build
[!Fugue-1.12.2-0.5.2.zip](https://github.com/CleanroomMC/Fugue/files/14074817/Fugue-1.12.2-0.5.2.zip)

**Comment by ZZZank** [comment]
<img width="885" alt="image" src="https://github.com/CleanroomMC/Fugue/assets/47418975/5d6483f3-1a64-43e5-82f1-0857a8d1a121">
I've tested its rendering in JEI, Creative Tab, and in-world, it seems working perfectly. Thanks!

**Comment by kappa-maintainer** [comment]
The original mixin was too tricky to be stable, glad the new one works
