### ISSUE TITLE
在加载到mxTune时候崩溃

### ISSUE THREAD

**Issue by liuzhi123hao** [CleanroomMC/Fugue#13]
安装mxTune（[mxTune - MC百科|最大的Minecraft中文MOD百科 (mcmod.cn)](https://www.mcmod.cn/class/13304.html)）会在加载到mxTune时候崩溃

logs:[Vanilla 1.12.2 Crash Report [#k98ZfNG] - mclo.gs](https://link.mcmod.cn/target/aHR0cHM6Ly9tY2xvLmdzL2s5OFpmTkc=)

crash report:[Forge 1.12.2 Crash Report [#mUKvHKo] - mclo.gs](https://link.mcmod.cn/target/aHR0cHM6Ly9tY2xvLmdzL21VS3ZIS28=)
（帮[lobster](https://center.mcmod.cn/423988/)[原址](https://www.mcmod.cn/class/9689.html)101楼

**Comment by kappa-maintainer** [comment]
已在测试分支修复
