### ISSUE TITLE
Fugue without `!` in front of filename will cause RFTools' Storage Scanner to crash

### ISSUE THREAD

**Issue by ZZZank** [CleanroomMC/Fugue#17]
This crash can be reproduced using(and only using)
- Cleanroom 3028
- Fugue 0.5.4
- rftools 7.73
- mcjtylib 3.5.4

After installing these, just open a Storage Scanner. 

What happened when Fugue's filename is `Fugue-1.12.2-0.5.4.jar`:
[crash-2024-02-12_10.11.39-client.txt](https://github.com/CleanroomMC/Fugue/files/14234887/crash-2024-02-12_10.11.39-client.txt)
```
java.lang.NullPointerException: Cannot invoke "mcjty.lib.gui.Scrollable.getFirstSelected()" because "this.scrollable" is null
	at mcjty.lib.gui.widgets.Slider.mouseWheel(Slider.java:178)
	at mcjty.lib.gui.widgets.AbstractContainerWidget.mouseWheel(AbstractContainerWidget.java:46)
	at mcjty.lib.gui.widgets.AbstractContainerWidget.mouseWheel(AbstractContainerWidget.java:46)
	at mcjty.lib.gui.Window.draw(Window.java:292)
	at mcjty.lib.gui.WindowManager.lambda$draw$3(WindowManager.java:87)
...
```

What happend when Fugue's filename is `!Fugue-1.12.2-0.5.4.jar`:
(Github somehow doesn't allow me to upload screenshot, it seems that there're some wierd format on my screenshot)
Everything seems working normally.

Given the fact that `!` in filename can affect even untouched mods, I think maybe Fugue should add an `!` in filename ahead of time when release(MixinBooter is already doing so, and that doesn't seem to violate anything)

**Comment by kappa-maintainer** [comment]
I want to add this by default too, but GitHub just removed it automatically
Will try to find another working char
But Fugue somehow patched mcjty is unintended. I will keep this PR open, so I can check it later

**Comment by ZZZank** [comment]
I found that in certain cases Fugue will crash RFTools even with `!` in filename. 
I can reporduece this crash by: 

- place a Storage Scanner, then power it
- bind it with a Storage Control Screen Module
- craft this module with Storage Tablet, power the tablet
- force load the chunk where such Storage Scanner is. I'm using FTBChunks
- go far away until Storage Scanner is not visible. View distance doesn't matter in my test. 
- open Storage Tablet
- crash

The modlist is the same as before, and the crash report is also the same. 
It seems that `go far away` is important for triggering this crash, because it won't crash when I was near such Storage Scanner

**Comment by kappa-maintainer** [comment]
Switched to `+`, but still need to investigate what's behind RFTools' crash

**Comment by kappa-maintainer** [comment]
Reproduced, just clicking Storage Scanner will crash the game like this

**Comment by kappa-maintainer** [comment]
RFTools must have some weird problem
The `scrollable` was null for no reason, but when I mixin into it and see what's going on it suddenly had a value
From this point, all rftool machines in this save are safe from crash now, even after I disabled the mixin or fugue. 
The same crash happened again in new save though

**Comment by kappa-maintainer** [comment]
Could you try if the latest build from action fix the problem?
I also get `Could not find component 'offset'!` when using scanner, but I have no idea if it is normal, you could check that too

**Comment by ZZZank** [comment]
I've tested the snapshot version from https://github.com/CleanroomMC/Fugue/actions/runs/8325910403, and the game runs runs for nearly an hour without crash, no matter how I opened the Storage Scanner. Cool!

But it finally crashed due to another mod FutureMC, which can be fixed with an addition to the config. I think I will make a PR for that soon. 

Maybe we can mark this issue as resolved now
