### ISSUE TITLE
安装mup后发生崩溃

### ISSUE THREAD

**Issue by liuzhi123hao** [CleanroomMC/Fugue#18]
日志：
[latest.log](https://github.com/CleanroomMC/Fugue/files/14295094/latest.log)
crash report：
[crash-2024-02-15_17.52.14-client.txt](https://github.com/CleanroomMC/Fugue/files/14295102/crash-2024-02-15_17.52.14-client.txt)
模组：
[!Fugue-1.12.2-0.5.4.zip](https://github.com/CleanroomMC/Fugue/files/14295111/Fugue-1.12.2-0.5.4.zip)
[mup-1.3.8.zip](https://github.com/CleanroomMC/Fugue/files/14295124/mup-1.3.8.zip)

**Comment by kappa-maintainer** [comment]
疑似mixin版本不兼容，试试这版
https://www.curseforge.com/minecraft/mc-mods/mup-eigencraft-unofficial-patch-reupload-with/files/4735866

**Comment by kappa-maintainer** [comment]
非官方版可正常运行
