### ISSUE TITLE
LiteLoader无法加载

### ISSUE THREAD

**Issue by liuzhi123hao** [CleanroomMC/Fugue#2]
在使用Cleanroom加载LiteLoader时，我的mc发生了崩溃，提示为
![6A](https://github.com/CleanroomMC/Fugue/assets/102130535/b47fc679-c4fe-4498-95d1-a45890d0996a)
做一下兼容

**Comment by kappa-maintainer** [comment]
你这提示和没有差不多
我们不计划兼容Liteloader，但我们鼓励把liteloader的模组移植到Forge（而且有部分模组已经在移植了）
