### ISSUE TITLE
Incompatibilities found

### ISSUE THREAD

**Issue by kreml-rumatschov** [CleanroomMC/Fugue#20]
Hello, first I would like to thank for your great work. It is truely a pleasure to see that even legacy Minecraft versions receive support to this date. However, I have found some incompatibilities I would like to report.

With the **IC2 Patcher** mod, the mod crashes due to not being able to use the Pack200 library. I assume that library has been removed at some point during the Java development process. Here is the crash log: https://mclo.gs/19xQRTn

I also found the **OpenFM** mod to be incompatible with CleanroomMC and needing a patch. Here is the crash log for that, but honestly I don't really know why it crashed: https://mclo.gs/J9ah6nk

Fortunately, both OpenFM and IC2 Patcher are licensed very permissively. Here is the respective source codes:
OpenFM: https://github.com/PC-Logix/OpenFM
IC2 Patcher: https://github.com/Su5eD/IC2-Patcher

My knowledge with Java is very much from the ass, therefore I sadly cannot be much help to you. If you want to know anything additional, I will respond promptly. Thank you.

**Comment by KorewaLidesu** [comment]
IC2 Patcher has been patched to work with Cleanroom iirc, check again

**Comment by kreml-rumatschov** [comment]
> IC2 Patcher has been patched to work with Cleanroom iirc, check again [Su5eD/IC2-Patcher@3cbde97](https://github.com/Su5eD/IC2-Patcher/commit/3cbde973c43fc51666c90ca0b19114f478de5006) You can download it as beta file from [CurseForge](https://www.curseforge.com/minecraft/mc-mods/ic2-patcher/files/4991810)

This is indeed true, I was stuck on an old version for whatever reason. OpenFM hasn't been updated since 2018 however. Just for quick reference, this is where the crash appears (line 26, called from 75 probably): https://github.com/PC-Logix/OpenFM/blob/master/src/main/java/pcl/OpenFM/misc/DepLoader.java

**Comment by KorewaLidesu** [comment]
Test with this artifact build
[openfm-0.1.0-dev.zip](https://github.com/CleanroomMC/Fugue/files/14467827/openfm-0.1.0-dev.zip)
Repo: https://github.com/KorewaLidesu/OpenFM/tree/1.12.2

**Comment by kreml-rumatschov** [comment]
Sorry, but it doesn't boot either. Compiled it myself, too, but no dice: https://mclo.gs/POt090K

**Comment by KorewaLidesu** [comment]
Sorry about the error, I forgot to remove it from the hook method.
Try recompile with new commit again. I'm busy this morning so I can't really help much. :sob:

**Comment by kappa-maintainer** [comment]
Just finish my refactor and checking this issue... OpenFM's problem is identical to OpenDisks and OpenSecurity's, which already been fixed for them
So I just need to add an extra class matching to fix it...

**Comment by kreml-rumatschov** [comment]
Sorry for the late reply, was busy in real life. After hearing that Fugue has the fix worked into it now I went to compiling it myself, but couldn't get it to boot. Have you tried building and launching yet?: https://mclo.gs/n2sn4Aw

**Comment by kappa-maintainer** [comment]
It's based on a local branch of cleanroom, please wait official release

**Comment by kappa-maintainer** [comment]
Should have fixed in 0.9.4, please test it with latest MMC pack
