### ISSUE TITLE
Caught exception from Railcraft (railcraft)

### ISSUE THREAD

**Issue by UraraChiya** [CleanroomMC/Fugue#22]
使用最新Release版的 railcraft-12.0.0 崩溃，日志如下 https://pastebin.com/jXrg8gRj

**Comment by jchung01** [comment]
I believe using latest BETA version of Railcraft (12.1.0-beta-8) fixes it, but there is an annoying beta message printed in chat everytime you join a world with this version.

**Comment by kappa-maintainer** [comment]
别用Release版，不管从兼容还是功能上都不行了
