### ISSUE TITLE
Crashes with fugue and LoliASM

### ISSUE THREAD

**Issue by daizu-007** [CleanroomMC/Fugue#32]
If you try to use Fugue 0.12.0-beta and LoliASM 5.19 at the same time, it will not start and will crash.
Mods:
CleanroomLoader 15.24.0.3034 (https://github.com/CleanroomMC/CleanroomMMC/actions/runs/8431472734)
Fugue 0.12.0-beta
LoliASM 5.19
Log:
https://mclo.gs/NPGfCnG

**Comment by kappa-maintainer** [comment]
Should have fixed in latest Cleanroom + Fugue
