### ISSUE TITLE
Survival Inc. mod could not load on CleanroomLoader.

### ISSUE THREAD

**Issue by daizu-007** [CleanroomMC/Fugue#34]
When I try to load the Survival Inc. mod with CleanroomLoader, it crashes.
Forge reads it fine.

Mods:
CleanroomLoader 15.24.0.3035 (https://github.com/CleanroomMC/CleanroomMMC/actions/runs/8580894704)
Fugue 0.13.0-beta
Survival Inc. 1.3.0

Log: 
https://mclo.gs/sNha74H

**Comment by kappa-maintainer** [comment]
Fixed in 0.14.0
