### ISSUE TITLE
Valkyrie mod could not load on latest CleanroomLoader.

### ISSUE THREAD

**Issue by daizu-007** [CleanroomMC/Fugue#35]
When I try to load the Valkyrie mod with the latest CleanroomLoader, it crashes.
Forge reads it fine.

Mods:
CleanroomLoader 15.24.0.3035 (https://github.com/CleanroomMC/Cleanroom/actions/runs/8580871663)
Fugue 0.13.0-beta
Red Core 0.6-Dev-3
Valkyrie 0.2

Log:
https://mclo.gs/RxrHcrb

**Comment by kappa-maintainer** [comment]
Reported to author, should be fixed in next Valkyrie release

**Comment by kappa-maintainer** [comment]
The author is lazy, gonna fix it in fugue for now
