### ISSUE TITLE
Fugue failing to patch Variegated

### ISSUE THREAD

**Issue by BigBoss1941** [CleanroomMC/Fugue#37]
a player at MBC got bricked out of their instance after days of playing, got thrown this error https://mclo.gs/JbETYKV If the tick speed in config is set to 20(mbc default), it crashes 
However setting it to 100 (mod default) will let the instance boot
Using exp, latest fugue. 
[variegated.zip](https://github.com/CleanroomMC/Fugue/files/15174970/variegated.zip)
Please find joined the Class Dump

**Comment by kappa-maintainer** [comment]
![Screenshot_20240501_231121](https://github.com/CleanroomMC/Fugue/assets/11038263/6bf69eab-971b-4c2d-8cc9-1f7a22caba28)
Bisect time!
