### ISSUE TITLE
FancyMenu crash

### ISSUE THREAD

**Issue by TheTzdDark** [CleanroomMC/Fugue#40]
Cleanroom: https://github.com/CleanroomMC/Cleanroom/releases/tag/0.2.1-alpha
Fugue: https://github.com/CleanroomMC/Fugue/releases/tag/0.14.12
FancyMenu: https://www.curseforge.com/minecraft/mc-mods/fancymenu/files/4655936
Java: zulu21.34.19-ca-jre21.0.3

Log: https://mclo.gs/V3j6u5z

**Comment by kappa-maintainer** [comment]
Can't reproduce by fancymenu itself, please try to find the minimal reproducible combination

**Comment by TheTzdDark** [comment]
Indeed, after checking purely with Fancy Menu everything works fine, I found what causes this crash.

It's all the fault of RandomPatches: https://www.curseforge.com/minecraft/mc-mods/randompatches-forge/files/3133651

When adding it to the client, this error appears, I also found that I need to disable in the config of this mod to solve it:
```
    # Set this to false to disable the Minecraft class patches (the Toggle Narrator keybind and custom window title/icon).
    # Default: true
    B:patchMinecraftClass=false
```

To be honest, it's enough for me to turn off this setting and that's it, but if you still want to fix it, then it will be great.

**Comment by kappa-maintainer** [comment]
I will check about it, random patches is probably loading the class in advanced, which may cause crash like this

**Comment by kappa-maintainer** [comment]
Further investigation shows the root cause is `com.therandomlabs.randompatches.core.RPClassWriter.getCommonSuperClass` loaded the class too early. That's a bug of RandomPatch and can be reproduced under Forge. We wouldn't patch non-Cleanroom problem, please contact the author instead.
