### ISSUE TITLE
LiteLoader crash

### ISSUE THREAD

**Issue by TheTzdDark** [CleanroomMC/Fugue#41]
Cleanroom: https://github.com/CleanroomMC/Cleanroom/releases/tag/0.2.1-alpha
Fugue: https://github.com/CleanroomMC/Fugue/releases/tag/0.14.12
LiteLoader: https://www.liteloader.com/download
Java: zulu21.34.19-ca-jre21.0.3

Log: https://mclo.gs/c0xYjwl

**Comment by kappa-maintainer** [comment]
Not supported.
