### ISSUE TITLE
Compatibility issues

### ISSUE THREAD

**Issue by QAQ330** [CleanroomMC/Fugue#44]
Cleanroom version: 0.2.2
Fugue version: 0.15.4
Java version: Java 21

* "MrTJPCore" and "ForgeMultipart" cause a crash

![image](https://github.com/CleanroomMC/Fugue/assets/149245477/c5b7cc50-0b47-44a6-88c9-dd2738e51863)

**Comment by QAQ330** [comment]
"Project Red" need "MrTJPCore" and "ForgeMultipart", but these mods cause a crash

**Comment by kappa-maintainer** [comment]
Please read Cleanroom readme and install [Scalar 2.11.1](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1)
