### ISSUE TITLE
打开Xaero's World Map的界面时, 无法通过鼠标滚轮缩放地图

### ISSUE THREAD

**Issue by MamekoCSc** [CleanroomMC/Fugue#45]
Cleanroom版本: 0.2.2
Fugue版本: 0.15.4*
Java版本: Java 21
Xaero's World Map版本: 1.38.8

*当我把Fugue版本回退到0.15.3后, 这个问题就不再出现

**Comment by kappa-maintainer** [comment]
已在0.15.5（自动发布中）修复
