### ISSUE TITLE
Crash with Computronics

### ISSUE THREAD

**Issue by Margatroidu** [CleanroomMC/Fugue#46]
### Cleanroom Version

0.2.2-alpha

### Java Version

Java 22

### Graphics Card Vendor

AMD/ATI

### Bug Report

Crash with [Computronics](https://wiki.vexatos.com/wiki:computronics)
[crash-2024-06-20_08.44.35-client.txt](https://github.com/user-attachments/files/15912647/crash-2024-06-20_08.44.35-client.txt)

### Mod List

FTB Revelation modpack that use Computronics mod

### MMC Instance Notes

?

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I have installed [Scalar 2.11.1](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
That's a crash between computronics and beta RailCraft
It should happen on Forge too, the only solution for now is to install the version of both mods from Tekkit 2 modpack
https://www.technicpack.net/modpack/tekkit-2.1935271/mods
