### ISSUE TITLE
Crash with RenderLib

### ISSUE THREAD

**Issue by Margatroidu** [CleanroomMC/Fugue#47]
### Cleanroom Version

0.2.2-alpha

### Java Version

Java 22

### Graphics Card Vendor

AMD iGPU

### Bug Report

Crashes with RenderLib on startup

[crash-2024-06-21_11.34.56-client.txt](https://github.com/user-attachments/files/15925026/crash-2024-06-21_11.34.56-client.txt)

### Mod List

RenderLib 
MixinBootstrap
Mixin Compatibility
Fugue 
Scalar 

### MMC Instance Notes

...

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I have installed [Scalar 2.11.1](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
Already fixed in action build of Clearoom

**Comment by Margatroidu** [comment]
> Already fixed in action build of Clearoom

But my game still crashes. What am I supposed to do?

**Comment by kappa-maintainer** [comment]
> > Already fixed in action build of Clearoom
> 
> But my game still crashes. What am I supposed to do?

Download from here:
https://github.com/CleanroomMC/CleanroomMMC/actions/
Login, click the latest entry and download the artifact at bottom
Unzip to install if you are using Windows
