### ISSUE TITLE
Crash with ValkyrienSkies

### ISSUE THREAD

**Issue by ZOMG4s** [CleanroomMC/Fugue#48]
### Cleanroom Version

0.2.2

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

[crash-2024-06-23_01.22.09-client.txt](https://github.com/user-attachments/files/15937578/crash-2024-06-23_01.22.09-client.txt)

### Mod List

Fugue
scalar
valkyrienskies

### MMC Instance Notes

...

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I have installed [Scalar 2.11.1](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
Try add `org.valkyrienskies.mod.common.ValkyrienSkiesMod` to Field.set list in fugue.cfg

**Comment by ZOMG4s** [comment]
it works. thanks
