### ISSUE TITLE
加入ShoulderSurfing崩溃

### ISSUE THREAD

**Issue by ukmojb** [CleanroomMC/Fugue#5]
[latest.log](https://github.com/CleanroomMC/Fugue/files/13948686/latest.log)

**Comment by ukmojb** [comment]
https://www.mcmod.cn/class/3305.html

**Comment by kappa-maintainer** [comment]
经典desc不兼容，我看看

**Comment by ukmojb** [comment]
还有SplashAnimation
https://www.mcmod.cn/class/3968.html
[crash-2024-01-16_18.37.00-client.txt](https://github.com/CleanroomMC/Fugue/files/13948706/crash-2024-01-16_18.37.00-client.txt)

**Comment by ukmojb** [comment]
> 经典desc不兼容，我看看

customloadingscreen的部分功能失效(time函数的失效,不确定有没有别的失效)

**Comment by ukmojb** [comment]
> 经典desc不兼容，我看看

Sound-Physics-1.12.2-1.1.0
TheBetweenlands-3.8.1-universal
一起装的时候崩溃
[crash-2024-01-16_20.37.28-client.txt](https://github.com/CleanroomMC/Fugue/files/13950016/crash-2024-01-16_20.37.28-client.txt)

**Comment by kappa-maintainer** [comment]
典型ModifyArgs错误……我去改成redirect算了

**Comment by ukmojb** [comment]
加油)))

**Comment by kappa-maintainer** [comment]
SoundPhysics修了，我重写了Mixin的一些实现
前面几个我有空再看看

**Comment by kappa-maintainer** [comment]
Shoulder Surfing Reloaded修了

**Comment by ukmojb** [comment]
> Shoulder Surfing Reloaded修了

不知为何删除水游技艺后却出现崩溃
[minecraft-exported-crash-info-2024-01-20T09-02-49.zip](https://github.com/CleanroomMC/Fugue/files/13996073/minecraft-exported-crash-info-2024-01-20T09-02-49.zip)
加了之后正常开启游戏

**Comment by kappa-maintainer** [comment]
疑似有高手多初始化了一份mixin，建议将mods文件夹按大小排序，打开大于1m的模组逐一检查是否有org/spongepowered/asm目录，有则删除

**Comment by ukmojb** [comment]
> org/spongepowered/asm

发现是3dSkinLayers-forge-mc1.12.2-1.2.0.jar搞得, 请问这个能解决吗))3d皮肤还挺好看的
还有为什么水游技艺不打算继续支持了啊

**Comment by kappa-maintainer** [comment]
因为ModifyArgs问题在mixin那边修好了

**Comment by ukmojb** [comment]
> 因为ModifyArgs问题在mixin那边修好了

意思是水游技艺可以直接加?

**Comment by kappa-maintainer** [comment]
要更新，我昨天应该发了个新版
但是fugue还没有配套更新，0.3.4多了不必要的修复还是会崩溃的……

**Comment by ukmojb** [comment]
> 要更新，我昨天应该发了个新版 但是fugue还没有配套更新，0.3.4多了不必要的修复还是会崩溃的……

新版水游技艺还是新版fugue)

**Comment by kappa-maintainer** [comment]
新版cleanroom
fugue还没更新，下一个版本能一起 用

**Comment by ukmojb** [comment]
> 新版cleanroom fugue还没更新，下一个版本能一起 用

谢谢)

**Comment by ukmojb** [comment]
> 因为ModifyArgs问题在mixin那边修好了 至于自带mixin的直接在jar删掉整个目录就行

[minecraft-exported-crash-info-2024-01-20T09-34-05.zip](https://github.com/CleanroomMC/Fugue/files/13996140/minecraft-exported-crash-info-2024-01-20T09-34-05.zip)
自带mixin的都删了,还是崩溃

**Comment by ukmojb** [comment]
![image](https://github.com/CleanroomMC/Fugue/assets/105061290/24b1dcfc-c698-472c-ab7a-af0c56de6890)
![image](https://github.com/CleanroomMC/Fugue/assets/105061290/e2c98e20-8a51-49bb-976d-c230fa8346ce)

**Comment by kappa-maintainer** [comment]
那是目录，这样搜怎么可能搜到
进Cleanroom的discord细说，我们这发一条我邮箱响一次，服务器频道也响一次

**Comment by ukmojb** [comment]
> 那是目录，这样搜怎么可能搜到 进Cleanroom的discord细说，我们这发一条我邮箱响一次，服务器频道也响一次

discord未响应)))网络不好

**Comment by ukmojb** [comment]
> 那是目录，这样搜怎么可能搜到 进Cleanroom的discord细说，我们这发一条我邮箱响一次，服务器频道也响一次

我该在哪个说)))
![image](https://github.com/CleanroomMC/Fugue/assets/105061290/3c3524d9-11d0-4d1c-9695-5419d1561c45)
