### ISSUE TITLE
 Botania flowers don't work with PaperFixes

### ISSUE THREAD

**Issue by nimuck** [CleanroomMC/Fugue#50]
### Cleanroom Version

0.2.2-alpha

### Java Version

Java 21

### Graphics Card Vendor

Intel iGPU

### Bug Report

[debug.log](https://github.com/user-attachments/files/16321611/debug.log)
[latest.log](https://github.com/user-attachments/files/16321612/latest.log)

It's not a startup crash, rather an in-game bug which makes all botania flowers non-functional, which renders entire mod useless. (though you can still bind them to mana pool, mana spreader...etc)

At first I thought it was a crash between two, but when tested on standard FML with minimal reproducible set below they worked well so I ended up reporting here

+I've also tested with all paperfixes' config options set to true/false but it didn't work, so it seems config doesn't matter.

### Mod List

minimal reproducible set:
[Botania+r1.10-364.4](https://www.curseforge.com/minecraft/mc-mods/botania/files/all?page=1&pageSize=20&version=1.12.2&showAlphaFiles=show)
[Baubles-1.12.2-1.0.6.0](https://www.curseforge.com/minecraft/mc-mods/baubles-lts/files/all?page=1&pageSize=20) (botania requirement)
[PaperFixes-1.1.0](https://www.curseforge.com/minecraft/mc-mods/paperfixes/files/all?page=1&pageSize=20)

you don't need fugue and scalar to replicate issue (I've tested)

### MMC Instance Notes

none

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I have installed [Scalar 2.11.1](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
PaperFix is known to be porting mixin patch from PaperMC blindly here
Since its patch amount is large, please open an issue on PaperFix's repository and see if the author have idea what is causing this

**Comment by nimuck** [comment]
Okay, though I don't know if the paperfix author knows about cleanroom, but anyway I'll try it.

**Comment by kappa-maintainer** [comment]
Fixed in PaperFix
