### ISSUE TITLE
failure with Solar Flux Reborn 

### ISSUE THREAD

**Issue by Igor5877** [CleanroomMC/Fugue#53]
### Cleanroom Version

0.2.2-alpha

### Java Version

Java 21

### Graphics Card Vendor

Intel iGPU

### Bug Report

[crash-2024-08-17_21.29.38-client.txt](https://github.com/user-attachments/files/16646320/crash-2024-08-17_21.29.38-client.txt)

### Mod List

[1.12.2]bspkrscore-universal-8.0.1.jar'
 additionallanterns-1.1.1b-forge-mc1.12.jar
 ae2stuff-extended-1.12.2-v0.8-0.2.1.jar
 ae2-uel-extended-v0.55.30-0.4.0.2-rv6-stable-7.jar
 AppleSkin-mc1.12-1.0.14.jar
 Aroma1997Core-1.12.2-2.0.0.2.jar
 Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.jar
 Avaritia-1.12.2-3.3.0.37-universal.jar
 Avaritiaddons-1.12.2-1.8.jar
 avaritiarecipemaker-1.0.0.jar
 Baubles-1.12-1.5.2.jar
 bdlib-1.14.4.1-mc1.12.2.jar
 beebetteratbees-1.12.2-2.0.3.jar
 BetterBedrockGenerator-1.12-6.1.1.jar
 BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar
 betterchat-1.5-for-1.12.2.jar
 BetterFps-1.4.8.jar
 binnie-mods-1.12.2-2.5.1.203.jar
 Bookshelf-1.12.2-2.3.590.jar
 BrandonsCore-1.12.2-2.4.20.162-universal.jar
 Chameleon-1.12-4.1.3.jar
 ChatCalculator-1.3.2.jar
 Clumps-3.1.2.jar
 CodeChickenLib-1.12.2-3.2.3.358-universal.jar
 CoFHCore-1.12.2-4.6.6.1-universal.jar
 CoFHWorld-1.12.2-1.4.0.1-universal.jar
 CoralReef-2.5-1.12.2.jar
 CraftTweaker2-1.12-4.1.20.697.jar
 CTM-MC1.12.2-1.0.2.31.jar
 Cucumber-1.12.2-1.1.3.jar
 denseneutroncollectors-1.1.jar
'DIvineAIOT v1.1 1.12.2.jar'
 DivineRPG-1.7.1.jar
 Draconic-Evolution-1.12.2-2.3.28.354-universal.jar
 ElevatorMod-1.12.2-1.3.14.jar
 EntityCulling-1.12.2-6.3.1.jar
 eternalsingularity-1.12.2-1.0.7.jar
 ExtremeReactors-1.12.2-0.4.5.68.jar
 FastFurnace-1.12.2-1.3.1.jar
 FastWorkbench-1.12.2-1.7.4.jar
 FluxNetworks-1.12.2-4.1.1.34.jar
 forestry_1.12.2-5.8.2.387.jar
 Forgelin-1.8.4.jar
 FpsReducer-mc1.12.2-1.20.jar
 FTBLib-5.4.7.2.jar
 FTBQuests-1202.9.0.15.jar
 +Fugue-1.12.2-0.15.9.jar
 future-mc-0.2.11.jar
 gendustry-1.6.5.8-mc1.12.2.jar
 GunpowderLib-1.12.2-1.1.jar
 IndustrialUpgrade-1.12.2-3.1.3.jar
 InventoryHUD-1.12.2.forge-3.4.4.jar
 InventoryTweaks-1.63.jar
 ironchest-1.12.2-7.0.72.847.jar
 ItemFilters-1.0.4.2.jar
 jei_1.12.2-4.16.1.301.jar
 jeibees-0.9.0.5-mc1.12.2.jar
 konkrete_forge_1.6.0_MC_1.12-1.12.2.jar
 lazy-ae2-1.12.2-1.1.26.jar
 libnine-1.12.2-1.2.1.jar
 loadmyresources_forge_1.0.4_MC_1.12-1.12.2.jar
 Mantle-1.12-1.3.3.55.jar
 materialis-1.12.2-1.2.5.jar
 MineTweakerRecipeMaker-1.12.2-1.2.2.30.jar
 _MixinBootstrap-1.1.0.jar
'[___MixinCompat-0.8___].jar'
 MobGrindingUtils-0.3.13.jar
 modtweaker-4.0.20.4.jar
 morepaintings-paintings-1.12.2-5.0.1.2.jar
 MouseTweaks-2.10-mc1.12.2.jar
 MTLib-3.0.7.jar
 MysticalAgradditions-1.12.2-1.3.2.jar
 MysticalAgriculture-1.12.2-1.7.5.jar
 MysticalAgriexpansion-1.12.2-0.4.jar
 NaturesCompass-1.12.2-1.8.5.jar
 OptiFine_1.12.2_HD_U_G5.jar
'Ore Visual Detector-2.0.2.jar'
 oxygen-core-1.12.2-0.11.4.jar
 oxygen-daily-rewards-1.12.2-0.11.2.jar
 p455w0rdslib-1.12.2-2.3.161.jar
 PackagedAuto-1.12.2-1.0.12.46.jar
 PackagedAvaritia-1.12.2-1.0.2.9.jar
 PackagedDraconic-1.12.2-1.0.0.13.jar
 Placebo-1.12.2-1.6.0.jar
 Power+Utilities.jar
 RedstoneFlux-1.12-2.1.1.1-universal.jar
 RenderLib-1.12.2-1.2.7.jar
 Simply+Quarries.jar
 Singularities-1.12.2-2.4.1.jar
 SolarFluxReborn_1.12.2-4.32r.jar
 spark-forge.jar
 StorageDrawers-1.12.2-5.5.0.jar
 supermartijn642configlib-1.1.6-forge-mc1.12.jar
 _supermartijn642corelib-1.1.17-forge-mc1.12.jar
 Surge-1.12.2-2.0.77.jar
 TConstruct-1.12.2-2.13.0.183.jar
 tesla-core-lib-1.12.2-1.0.18.jar
 theoneprobe-1.12-1.4.28.jar
 ThermalCultivation-1.12.2-0.3.6.1-universal.jar
 ThermalDynamics-1.12.2-2.5.6.1-universal.jar
 ThermalExpansion-1.12.2-5.5.7.1-universal.jar
 ThermalFoundation-1.12.2-2.6.7.1-universal.jar
 ThermalInnovation-1.12.2-0.3.6.1-universal.jar
 TinkerToolLeveling-1.12.2-1.1.0.jar
 tlskincape1.12.2-1.4.jar
 trashcans-1.0.17-forge-mc1.12.jar
'VariedCommodities_1.12.2-(31Mar23).jar'
 WanionLib-1.12.2-2.9.jar
 WrapUp-1.12-1.1.3.jar
 Xaeros_Minimap_24.2.0_Forge_1.12.jar
 Xtones-1.2.2.jar
 zerocore-1.12.2-0.1.2.9.jar

### MMC Instance Notes

...

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I have installed [Scalar 2.11.1](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
Your SolarFluxReborn mod is seriously outdated, update to 12.4.11
