### ISSUE TITLE
kablade模组启动崩溃

### ISSUE THREAD

**Issue by LingyuDz** [CleanroomMC/Fugue#54]
看起来好像是mixin的问题，我把版本降低到1.3-b就可以了，因为这个版本有要求前置mixinbooter，高版本就不行了，可是少了好多东西

**Comment by kappa-maintainer** [comment]
你这一个日志没有下次我看见就直接close了
试了下将`com.wjx.kablade.mixin.KabladeMixinTweak`加到fugue.cfg的getCodeSource列表里应该就行

**Comment by ZZZank** [comment]
需要崩溃日志与latest.log。
KaBlade开源的代码非常混乱，还不给日志，诊断起来无异于闭眼开车

**Comment by LingyuDz** [comment]
[minecraft-exported-crash-info-2024-08-25T17-10-39.zip](https://github.com/user-attachments/files/16739595/minecraft-exported-crash-info-2024-08-25T17-10-39.zip)
补上了，不好意思

**Comment by LingyuDz** [comment]
> 你这一个日志没有下次我看见就直接close了 试了下将`com.wjx.kablade.mixin.KabladeMixinTweak`加到fugue.cfg的getCodeSource列表里应该就行

我加上去然后保存了，不过还是会崩溃
这个是日志
[minecraft-exported-crash-info-2024-08-25T17-26-20.zip](https://github.com/user-attachments/files/16739632/minecraft-exported-crash-info-2024-08-25T17-26-20.zip)
![dfe0dae8f91d7a9af98f81169e65b1c9](https://github.com/user-attachments/assets/a88a230b-6e46-4124-9981-490c02ffd4c0)

**Comment by LingyuDz** [comment]
> 你这一个日志没有下次我看见就直接close了 试了下将`com.wjx.kablade.mixin.KabladeMixinTweak`加到fugue.cfg的getCodeSource列表里应该就行

对不起！！我忘记把fugue加上去了，补上这个是可以的

**Comment by kappa-maintainer** [comment]
fugue忘装还行，那关了
