### ISSUE TITLE
与CB Multipart启动崩溃

### ISSUE THREAD

**Issue by liuzhi123hao** [CleanroomMC/Fugue#56]
### Cleanroom Version

0.2.3-alpha+build.0.run.688

### Java Version

Java 22

### Graphics Card Vendor

NVidia

### Bug Report

[crash-2024-08-30_16.33.57-client.txt](https://github.com/user-attachments/files/16814149/crash-2024-08-30_16.33.57-client.txt)
[2024-08-30-5.log.gz](https://github.com/user-attachments/files/16814153/2024-08-30-5.log.gz)
[latest.log](https://github.com/user-attachments/files/16814155/latest.log)

### Mod List

[crash-2024-08-30_16.33.57-client.txt](https://github.com/user-attachments/files/16814149/crash-2024-08-30_16.33.57-client.txt)

### MMC Instance Notes

hmcl

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I have installed [Scalar 2.11.1](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
Scalar得装2.11.1的
