### ISSUE TITLE
启动崩溃

### ISSUE THREAD

**Issue by NineDays-SuYue** [CleanroomMC/Fugue#57]
### Cleanroom Version

0.2.3-alpha

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

https://mclo.gs/Eu0PRV3  前置LLibrary 1.7.20启动崩溃、降低版本1.7.18启动成功、冰火传说1.9.1启动崩溃、禁用Fugue启动成功

### Mod List

FML: MCP 9.42 LoliASM 5.20 Cleanroom 0.2.3-alpha Optifine OptiFine_1.12.2_HD_U_G6_pre1 28 mods loaded, 27 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                  | Version                    | Source                                                  | Signature                                |
       |:----- |:------------------- |:-------------------------- |:------------------------------------------------------- |:---------------------------------------- |
       | LCH   | minecraft           | 1.12.2                     | minecraft.jar                                           | None                                     |
       | LCH   | mcp                 | 9.42                       | minecraft.jar                                           | None                                     |
       | LCH   | configanytime       | 3.0                        | cleanroom-0.2.3-alpha-universal.jar                     | None                                     |
       | LCH   | cleanroom           | 0.2.3-alpha                | cleanroom-0.2.3-alpha-universal.jar                     | None                                     |
       | LCH   | FML                 | 8.0.99.99                  | cleanroom-0.2.3-alpha-universal.jar                     | None                                     |
       | LCH   | forge               | 14.23.5.2860               | cleanroom-0.2.3-alpha-universal.jar                     | None                                     |
       | LCH   | mixinbooter         | 10.0                       | cleanroom-0.2.3-alpha-universal.jar                     | None                                     |
       | LCH   | foamfixcore         | 7.7.4                      | minecraft.jar                                           | None                                     |
       | LCH   | fugue               | 1.12.2-0.16.3              | !Fugue-1.12.2-0.16.3.jar                                | None                                     |
       | LCH   | stellar_core        | 1.3.4                      | [优化-星核]StellarCore-1.3.4.jar                            | None                                     |
       | LCH   | shutupmodelloader   | 1.0.0                      | [优化-模型加载日志]shutupmodelloader-1.12.2-1.0.0.jar           | None                                     |
       | LCH   | foamfix             | @VERSION@                  | [优化-泡沫修复]foamfix-0.10.15-1.12.2.jar                     | None                                     |
       | LCH   | jei                 | 4.25.5                     | [辅助-HEI物品管理器]HadEnoughItems_1.12.2-4.25.5.jar           | None                                     |
       | LCH   | loliasm             | 5.20                       | [优化-游戏时刻]censoredasm5.20.jar                            | None                                     |
       | LCH   | particleculling     | v1.4.3                     | [优化-粒子渲染机制]particleculling-1.12.2-v1.4.3.jar            | None                                     |
       | LCH   | universaltweaks     | 1.12.1                     | [优化-通用修改]UniversalTweaks-1.12.2-1.12.1.jar              | None                                     |
       | LCH   | homoium             | 1.0.8                      | [优化-铜]homoium-1.0.8.jar                                 | None                                     |
       | LCH   | twilightforest      | 3.11.2000                  | [冒险-暮色森林]twilightforest-1.12.2-3.11.2000.jar            | None                                     |
       | LCH   | theaurorian         | 1.12.2-Release             | [冒险-极光幽境]theaurorian-1.12.2-1.2.jar                     | None                                     |
       | LCH   | forgelin_continuous | 2.0.20.0                   | [前置-Forgelin]Forgelin-Continuous-2.0.20.0.jar           | None                                     |
       | LCH   | forgelin            | 1.8.4                      | [前置-Forgelin]Forgelin-Continuous-2.0.20.0.jar           | None                                     |
       | LCH   | extendedae          | 1.12-0.0.1                 | [科技-AE拓展]ExtendedAE-1.12-0.0.1.jar                      | None                                     |
       | LCH   | appliedenergistics2 | 4528738                    | [科技-应用能源非官方延续版]ae2-uel-4528738.jar                      | None                                     |
       | LCH   | betterp2p           | 1.12.2-1.2.3-extended_life | [科技-AE更好的P2P支持]betterp2p-1.12.2-1.2.3-extended_life.jar | None                                     |
       | LCH   | nae2                | 1.6.4                      | [科技-AE附加工具]nae2-1.6.4.jar                               | None                                     |
       | LCH   | llibrary            | 1.7.18                     | llibrary-1.7.18-1.12.2.jar                              | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCH   | iceandfire          | 1.9.1                      | iceandfire-1.9.1-1.12.2.jar                             | None                                     |
       | UD    | scalar              | 2.11.1                     | minecraft.jar                                           | None                                     |
  Loaded coremods (and transformers): HomoiumCorePlugin ([优化-铜]homoium-1.0.8.jar)
                                        
                                      ExtendedAE ([科技-AE拓展]ExtendedAE-1.12-0.0.1.jar)
                                        com.github.glodblock.eae.coremod.EAEClassTransformer
                                      iceandfire (iceandfire-1.9.1-1.12.2.jar)
                                        com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
                                      Forgelin-Continuous ([前置-Forgelin]Forgelin-Continuous-2.0.20.0.jar)
                                        
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      LoliASM ([优化-游戏时刻]censoredasm5.20.jar)
                                        
                                      ParticleCullingLoadingPlugin ([优化-粒子渲染机制]particleculling-1.12.2-v1.4.3.jar)
                                        
                                      NAE2-Core ([科技-AE附加工具]nae2-1.6.4.jar)
                                        
                                      UniversalTweaksCore ([优化-通用修改]UniversalTweaks-1.12.2-1.12.1.jar)
                                        
                                      ScalarLoadingPlugin ([前置-库]scalar-1.12.2-2.11.1.jar)
                                        
                                      Fugue (!Fugue-1.12.2-0.16.3.jar)
                                        
                                      AE2ELCore ([科技-应用能源非官方延续版]ae2-uel-4528738.jar)
                                        appeng.core.transformer.AE2ELTransformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) ([优化-泡沫修复]foamfix-0.10.15-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      StellarCoreEarlyMixinLoader ([优化-星核]StellarCore-1.3.4.jar)
                                        
                                      MixinBooter (cleanroom-0.2.3-alpha-universal.jar)
  GL info: No OpenGL context found in the current thread
  AE2 Version: stable 4528738 for Forge 14.23.5.2847
  Suspected Mods: LLibrary (llibrary)

### MMC Instance Notes

并未使用

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I have installed [Scalar 2.11.1](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
homoium删掉试试
这崩溃疑似上了ASM，需要一个最小可重现模组组合

**Comment by NineDays-SuYue** [comment]
> homoium删掉试试 这崩溃疑似上了ASM，需要一个最小可重现模组组合

https://mclo.gs/J6R0T5j  以删除homoium但并未解决、我尝试下调冰火传说版本来获取兼容
