### ISSUE TITLE
与Botania Tweaks冲突

### ISSUE THREAD

**Issue by Flukesuki** [CleanroomMC/Fugue#6]
虽然看介绍好像是修复了但是还是因为冲突而启动不了游戏 下面是latest(单独加入fugue和bt，在cleanroom加载器环境）
https://mclo.gs/ddsqS5O

**Comment by kappa-maintainer** [comment]
fugue文件名开头要加个感叹号

**Comment by Flukesuki** [comment]
> fugue文件名开头要加个感叹号

okok可以了，居然犯了这么低级错误
