### ISSUE TITLE
Help with static final field has no write access (Dynamic Trees for The Betweenlands)

### ISSUE THREAD

**Issue by aking4125** [CleanroomMC/Fugue#61]
### Cleanroom Version

0.2.3-alpha

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

https://mclo.gs/RWXZgLA

[debug.log](https://github.com/user-attachments/files/17434561/debug.log)

I was looking at the config. Adding one of the classes could help prevent the crash but I'm not sure which class to add if at all. Any help with this if possible?

https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-the-betweenlands

https://www.curseforge.com/minecraft/mc-mods/angry-pixel-the-betweenlands-mod

Apologies if this isn't the right place to report it.

### Mod List

- [Forestry](https://www.curseforge.com/projects/59751) [5.8.2.422] by SirSengir, mezz
- [Thaumic Bases](https://www.curseforge.com/projects/293406) [3.6.011.0] by Rumaruka, AeXiaohu, keletu
- [Bookshelf](https://www.curseforge.com/projects/228525) [2.3.590] by darkhax, lclc98
- [Lootr](https://www.curseforge.com/projects/361276) [0.6.2] by Noobanidus, embeddedt
- [RoughlyEnoughIDs](https://www.curseforge.com/projects/629017) [2.2.1] by Runemoro, ZombieHDGaming
- [Legendary Tooltips](https://www.curseforge.com/projects/532127) [1.1.11] by Grend
- [LLibrary](https://www.curseforge.com/projects/243298) [1.7.20-1.12.2] by iLexiconn, gegy1000
- [Patchouli](https://www.curseforge.com/projects/306770) [1.0-23.6] by Vazkii
- [Pam's DesertCraft](https://www.curseforge.com/projects/221911) [1.12.2c] by Pamela Collins
- [Universal Tweaks](https://www.curseforge.com/projects/705000) [1.12.0] by ACGaming
- [Iron Chest](https://www.curseforge.com/projects/228756) [1.12.2-7.0.67.844] by cpw
- memory_repo
- [GregTech Food Option](https://www.curseforge.com/projects/477021) [1.12.1] by bruberu
- [Snad](https://www.curseforge.com/projects/241344) [1.12.1-1.7.09.16a] by TheRoBrit
- [PipeBlocker](https://www.curseforge.com/projects/896289) [1.1.3] by embeddedt
- [Botania](https://www.curseforge.com/projects/225643) [r1.10-364.4] by Vazkii, williewillus, wiiv, dylan4ever
- [Neat](https://www.curseforge.com/projects/238372) [1.4-17] by Vazkii
- [Dynamic Trees for The Twilight Forest](https://www.curseforge.com/projects/391986) [1.12.2-1.2.3] by Max Hyper
- [Farming for Blockheads](https://www.curseforge.com/projects/261924) [3.1.28] by BlayTheNinth
- [GregTech](https://www.curseforge.com/projects/557242) [2.8.10-beta] by serenibyss, TechLord22, KilaBash, Archengius, Exidex, BloodAsp, Muramasa, GregoriusT
- [Serene Seasons](https://www.curseforge.com/projects/291874) [1.2.18] by Adubbz, Forstride
- [Stellar Core](https://www.curseforge.com/projects/1064321) [${version}] by Kasumi_Nova
- [JourneyMap](https://www.curseforge.com/projects/32274) [1.12.2-5.7.1p2] by techbrew, mysticdrew
- [The Betweenlands](https://www.curseforge.com/projects/243363) [3.9.6] by Angry Pixel
- [CodeChicken Lib](https://www.curseforge.com/projects/242818) [3.2.3.358] by ChickenBones, covers1624
- [Snow! Real Magic!](https://www.curseforge.com/projects/308663) [0.7.1] by Snownee
- [Dynamic Trees for The Betweenlands](https://www.curseforge.com/projects/473277) [1.0.3] by Max Hyper
- [TorchMaster](https://www.curseforge.com/projects/254268) [1.8.5.0] by xalcon
- [Trash Cans](https://www.curseforge.com/projects/394535) [1.0.18] by SuperMartijn642
- [GregTech Drawers](https://www.curseforge.com/projects/845779) [1.0.7] by integerlimit_, ung3froren, Raptor__
- [Blue Skies](https://www.curseforge.com/projects/312918) [2827455]
- [AutoRegLib](https://www.curseforge.com/projects/250363) [1.3-32] by Vazkii
- [Farsight](https://www.curseforge.com/projects/495693) [1.6] by Someaddon
- [Pam's Clay Spawn](https://www.curseforge.com/projects/221913) [1.0] by Pamela Collins
- [MixinBooter](https://www.curseforge.com/projects/419286) [9.4] by Rongmario
- [Dynamic Trees for Quark](https://www.curseforge.com/projects/386753) [1.12.2-1.0.6] by Max Hyper
- [Storage Drawers](https://www.curseforge.com/projects/223852) [5.5.2] by jaquadro
- [Advancement Plaques](https://www.curseforge.com/projects/499826) [${version}] by Grend
- [Ender Skills](https://www.curseforge.com/projects/391325) [${version}] by cybercat5555, Arekkuusu, Pandize
- [Hunger In Peace](https://www.curseforge.com/projects/224473) [1.0.0] by squeek
- [KleeSlabs](https://www.curseforge.com/projects/241895) [5.4.12] by BlayTheNinth
- [LoliASM](https://www.curseforge.com/projects/460609) [5.20] by Rongmario
- [ASMC](https://www.curseforge.com/projects/364982) [2902440] by AstroTibs
- [PaperFixes](https://www.curseforge.com/projects/961366) [1.3.1] by Elephant_1214
- [Pam's Simple Recipes](https://www.curseforge.com/projects/221915) [1.0] by Pamela Collins
- [FastFurnace](https://www.curseforge.com/projects/299540) [1.12.2-1.3.1] by Shadows_of_Fire
- [The Aether](https://www.curseforge.com/projects/255308) [v1.5.3.2] by bconlon, Oscar Payn, Hugo Payn, JellySquid
- [Simple Text Overlay](https://www.curseforge.com/projects/321283) [1.12.2-0.5.0.0] by wendall911
- [Carry On](https://www.curseforge.com/projects/274259) [1.12.3] by Tschipp, Purplicious_Cow, cy4n
- [Fluidlogged API](https://www.curseforge.com/projects/485654) [v2.2.4-mc1.12.2] by jbredwards
- [Dynamic Trees for Forbidden & Arcanus](https://www.curseforge.com/projects/416698) [1.12.2-1.0.1] by Max Hyper
- [Champions](https://www.curseforge.com/projects/418112) [1.12.2-1.0.11.10] by C4
- [Pam's BreadCraft](https://www.curseforge.com/projects/446100) [1.1.0] by QuackAndCheese
- [Open Terrain Generator](https://www.curseforge.com/projects/265894) [1.12.2-v9.5-R2] by PeeGee85, Authvin, SuperCoder79, Josh/Coll1234567, RutgerKok, TimeThor, Khorn/Wickth, Olof Cayorion Larsson
- [Nutrition Unofficial Extended Life](https://www.curseforge.com/projects/964516) [4.13.0] by Katatsumuri.pan
- [Dynamic Trees TC](https://www.curseforge.com/projects/292752) [1.12.2-1.4.2] by mangoose
- [Controlling](https://www.curseforge.com/projects/250398) [3.0.12.4] by Jaredlll08
- [FTB Ultimine](https://www.curseforge.com/projects/386134) [1202.3.5] by LatvianModder
- [CreativeCore](https://www.curseforge.com/projects/257814) [1.10] by CreativeMD, N247S
- [Building Gadgets](https://www.curseforge.com/projects/298187) [2.8.4] by Direwolf20
- [Enchantment Descriptions](https://www.curseforge.com/projects/250419) [1.1.20] by Darkhax
- [Just Enough Resources](https://www.curseforge.com/projects/240630) [0.9.3] by way2muchnoise
- [Pam's HarvestCraft](https://www.curseforge.com/projects/221857) [1.12.2zg] by Pamela Collins
- [Mouse Tweaks](https://www.curseforge.com/projects/60089) [NONE] by Ivan Molodetskikh (YaLTeR)
- [Mystical World](https://www.curseforge.com/projects/282940) [1.12.2-1.11.0] by Noobanidus, EpicSquid, Martacus, Davoleo, Kalaxi, Vulpie
- [Silent Lib](https://www.curseforge.com/projects/242998) [3.0.14] by SilentChaos512
- [Alfheim](https://www.curseforge.com/projects/910715) [1.4] by Red Studio
- [The Twilight Forest](https://www.curseforge.com/projects/227639) [3.11.1021] by Benimatic, AtomicBlom, Drullkus, Killer_Demon, quadraxis, Tamaized, williewillus
- Vintagium [0.1] by NanoLive, embeddedt, CaffeineMC
- [Placebo](https://www.curseforge.com/projects/283644) [1.12.2-1.6.1] by Shadows_of_Fire
- [Fugue](https://www.curseforge.com/projects/1005815) [0.16.3] by kappa_maintainer
- [Better Foliage](https://www.curseforge.com/projects/228529) [2.3.2] by octarine-noise (code), Meringue (textures)
- [Crafting Tweaks](https://www.curseforge.com/projects/233071) [8.1.9] by BlayTheNinth
- [Vampirism](https://www.curseforge.com/projects/233029) [1.6.2] by maxanier, Cheaterpaul
- [Forgelin-Continuous](https://www.curseforge.com/projects/456403) [2.0.0.0] by ChAoS_UnItY
- [Mowzie's Mobs](https://www.curseforge.com/projects/250498) [1.5.8] by BobMowzie, pau101
- [Better Combat](https://www.curseforge.com/projects/541058) [1.5.6] by Ironfists, SanAndreasP, Burgy
- [GeckoLib Example Mod](https://www.curseforge.com/projects/388172) [3.0.31
] by Gecko, Eliot
- [YUNG's Better Caves](https://www.curseforge.com/projects/340583) [1.12.2-2.0.4] by YUNGNICKYOUNG
- [Dynamic Trees for Forestry](https://www.curseforge.com/projects/401558) [1.12.2-1.0.10] by Max Hyper
- [Aquaculture](https://www.curseforge.com/projects/60028) [1.12.2-1.6.8] by Team Metallurgy
- [Dynamic Trees for The Aether](https://www.curseforge.com/projects/387443) [1.0.14] by Max Hyper
- [Dynamic Trees for Thaumcraft Addons](https://www.curseforge.com/projects/386768) [1.12.2-1.1.3] by Max Hyper
- [Traveler's Backpack](https://www.curseforge.com/projects/321117) [1.0.35] by Tiviacz1337
- [Aqua Acrobatics](https://www.curseforge.com/projects/321792) [1.15.4] by Fuzs, embeddedt
- [Hunger Overhaul](https://www.curseforge.com/projects/224476) [1.3.3.jenkins148] by iguana_man, Parker8283, progwml6, squeek502, alexbegt
- [Extra Utilities 2](https://www.curseforge.com/projects/225561) [${version}] by RWTema
- [Dynamic Trees for Integrated Dynamics](https://www.curseforge.com/projects/364983) [1.12.2-1.0.4] by Max Hyper
- [Waystones](https://www.curseforge.com/projects/245755) [4.1.0] by BlayTheNinth
- Pam's BrewCraft [1.0] by ExampleDude
- [ConfigAnytime](https://www.curseforge.com/projects/870276) [3.0] by CleanroomMC
- [YUNG's Better Mineshafts](https://www.curseforge.com/projects/389665) [1.12.2-2.2.1] by YUNGNICKYOUNG
- [VintageFix](https://github.com/embeddedt/VintageFix) [0.5.1-ci.200] by embeddedt
- [Cooking for Blockheads](https://www.curseforge.com/projects/231484) [6.5.0] by BlayTheNinth
- [AppleCore](https://www.curseforge.com/projects/224472) [2969118]
- [Scaling Health](https://www.curseforge.com/projects/248027) [1.3.42] by SilentChaos512
- [Tips](https://www.curseforge.com/projects/306549) [1.0.9] by Darkhax
- [Dark Utilities](https://www.curseforge.com/projects/242195) [1.8.230] by Darkhax
- [TrashSlot](https://www.curseforge.com/projects/235577) [8.4.10] by BlayTheNinth
- OpenTerrainGenerator
- [NetherPortalFix](https://www.curseforge.com/projects/241160) [5.3.17] by BlayTheNinth
- [BetterNether: RotN Edition](https://www.curseforge.com/projects/878052) [1.12.2-0.2.0.2] by paulevs, TwilightForest, democat3457
- [Iron Furnaces](https://www.curseforge.com/projects/237664) [1.3.5] by XenoMustache
- [Rough Mobs Revamped](https://www.curseforge.com/projects/360795) [1.12.2-2.3.23] by p1ut0nium_94, Lellson
- [The Spice of Life](https://www.curseforge.com/projects/220811) [1.3.12] by squeek
- [Simply Light](https://www.curseforge.com/projects/300331) [1.12.2-0.8.7] by Flanks255
- [Ice and Fire: RotN Edition](https://www.curseforge.com/projects/457668) [1.9.1-1.3.3] by Alexthe666, Raptorfarian, Asterixxx, Sekretone, democat3457
- [CosmeticArmorReworked](https://www.curseforge.com/projects/237307) [1.12.2-v5a] by zlainsama
- [The One Smeagle](https://www.curseforge.com/projects/977883) [1.12-1.0.0] by McJty, smeagle
- [SuperMartijn642's Core Lib](https://www.curseforge.com/projects/454372) [1.1.17+a] by SuperMartijn642
- [CTM](https://www.curseforge.com/projects/267602) [MC1.12.2-1.0.2.31] by tterrag, Drullkus, minecreatr
- [Dynamic Trees](https://www.curseforge.com/projects/252818) [1.12.2-0.9.29] by FerreusVeritas
- [Biomes O' Plenty](https://www.curseforge.com/projects/220318) [7.0.1] by Adubbz, Amnet, Cheeserolls, Forstride, ted80
- [Apotheosis](https://www.curseforge.com/projects/313970) [1.12.2-1.12.5] by Shadows_of_Fire
- [AppleSkin](https://www.curseforge.com/projects/248787) [1.0.14] by squeek
- [MmmMmmMmmMmm](https://www.curseforge.com/projects/225738) [1.12-1.14] by boni
- [Natura](https://www.curseforge.com/projects/74120) [1.12.2-4.3.2.69] by mDiyo, Slime Knights
- [Scalar](https://www.curseforge.com/projects/1012168) [2.11.1-2] by CleanroomMC, kappa_maintainer
- [LemonLib](https://www.curseforge.com/projects/306926) [1.12.2-1.3.0] by Lemons
- [Had Enough Items](https://www.curseforge.com/projects/557549) [4.25.5] by mezz, Rongmario
- [Cyclops Core](https://www.curseforge.com/projects/232758) [1.12.2-1.6.7] by rubensworks (aka kroeserr), immortaleeb (aka _EeB_)
- [Dynamic Trees PHC](https://www.curseforge.com/projects/307560) [2.0.6] by ferreusveritas, Max Hyper
- [Tinkers' Construct](https://www.curseforge.com/projects/74072) [1.12.2-2.13.0.183] by boni, KnightMiner
- [Dynamic Trees for Plants](https://www.curseforge.com/projects/395795) [1.12.2-1.0.3] by Max Hyper
- [Dynamic Trees for Vampirism](https://www.curseforge.com/projects/418326) [1.12.2-1.0.1] by Harley O'Connor
- [Bubbles](https://www.curseforge.com/projects/995393) [1.5.2-bubbles-2.2b-1] by Surreal
- [DregoraOP](https://www.curseforge.com/projects/817731) [1.0] by NLBlackEagle
- [Mantle](https://www.curseforge.com/projects/74924) [1.3.3.55] by boni, progWML6, Alexbegt
- [AmbientSounds](https://www.curseforge.com/projects/254284) [3516274] by CreativeMD
- [Chameleon](https://www.curseforge.com/projects/230497) [1.12-4.1.3] by jaquadro
- [Hardcore Darkness](https://www.curseforge.com/projects/225957) [2.0] by lumien
- [Nature's Compass](https://www.curseforge.com/projects/252848) [1.12.2-1.8.5] by ChaosTheDude
- [Thaumcraft](https://www.curseforge.com/projects/223628) [1.12.2-6.1.BETA26] by Azanor
- [Gregicality Multiblocks](https://www.curseforge.com/projects/564858) [1.2.11] by TechLord22
- [Tough As Nails](https://www.curseforge.com/projects/246391) [3.1.0] by Adubbz, Forstride
- [Quark: RotN Edition](https://www.curseforge.com/projects/417392) [r1.6-188] by Vazkii, wiiv, democat3457, Asterixxx, Yeelp
- [Mystical Lib](https://www.curseforge.com/projects/277064) [1.12.2-1.13.0] by EpicSquid, Elucent
- [Dynamic Trees for Mystical World](https://www.curseforge.com/projects/417864) [1.12.2-1.0.1] by Max Hyper, Harley O'Connor
- [Greenery](https://www.curseforge.com/projects/574029) [5.1] by TeksturePako
- [1.13 Water Mechanics](https://www.curseforge.com/projects/327277) [1.0.3] by xFra.
- [Dynamic Trees for Atum](https://www.curseforge.com/projects/408807) [1.12.2-1.0.4] by Max Hyper
- [Forbidden & Arcanus](https://www.curseforge.com/projects/309858) [1.12.2-1.1.4] by stal111, Xesar_Zorak
- [Pam's BoneCraft](https://www.curseforge.com/projects/221912) [3123986]
- [Red Core](https://www.curseforge.com/projects/873867) [0.6-Dev-7] by Red Studio
- [CommonCapabilities](https://www.curseforge.com/projects/247007) [1.12.2-2.4.8] by rubensworks (aka kroeserr)
- 1.12.2
- [Pick Up Notifier](https://www.curseforge.com/projects/351441) [1.1.5] by Fuzs
- [Dynamic Trees BOP](https://www.curseforge.com/projects/289529) [1.12.2-1.5.2] by mangoose
- [Dynamic Trees for Extra Utilities 2](https://www.curseforge.com/projects/386760) [1.12.2-1.1.0] by Max Hyper
- [Dynamic Trees for Natura](https://www.curseforge.com/projects/366216) [1.12.2-1.1.7] by Max Hyper
- [Better Builder's Wands](https://www.curseforge.com/projects/238403) [0.13.2] by Portablejim
- [Atum 2](https://www.curseforge.com/projects/59621) [1.12.2-2.0.20] by Shadowclaimer, Girafi, RebelKeithy
- [SerializationIsBad](https://www.curseforge.com/projects/896591) [5187152]
- [Better Advancements](https://www.curseforge.com/projects/272515) [0.1.0] by way2muchnoise
- [Dynamic Trees for Tinkers' Construct](https://www.curseforge.com/projects/386747) [1.12.2-1.2.7] by Max Hyper
- [Plants](https://www.curseforge.com/projects/257229) [1.12.2-2.10.7] by Shadows_of_Fire
- [Dynamic Trees for Pam's Trees](https://www.curseforge.com/projects/408974) [1.12.2-1.0.5] by Max Hyper
- [Highlighter](https://www.curseforge.com/projects/521590) [1.1.7] by Grend
- [Oceanic Expanse](https://www.curseforge.com/projects/840576) [1.1.4] by Sir Squidly
- [Integrated Dynamics](https://www.curseforge.com/projects/236307) [1.12.2-1.1.11] by rubensworks (aka kroeserr)
- [Comforts](https://www.curseforge.com/projects/276951) [1.12.2-1.4.1.3] by C4
- [Arcane World](https://www.curseforge.com/projects/475553) [1.12.2-0.1.0] by Lemons

### MMC Instance Notes

Nothing on notes.

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I have installed [Scalar 2.11.1](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by xskutsu** [comment]
I randomly started having the same issue with Quark: RotN Edition. Only happens with cleanroom

https://mclo.gs/2CiI3pA

**Comment by Rongmario** [comment]
For OP, In `Reflection Patch Target List` in fugue's config, add `maxhyper.dynamictreestbl.compat.RegistryReplacements`.

For @xskutsu install Fugue.
