### ISSUE TITLE
Crash with PolyFrost mods

### ISSUE THREAD

**Issue by nimuck** [CleanroomMC/Fugue#63]
### Cleanroom Version

action #759

### Java Version

Java 22

### Graphics Card Vendor

Intel iGPU

### Bug Report

1. Game crashes instantly when you try to open OneConifig in-game by rshift or /oneconfig, which makes all polyfrost mod unusable.
[crash-2024-11-07_00.46.46-client.txt](https://github.com/user-attachments/files/17649828/crash-2024-11-07_00.46.46-client.txt)
[debug.log](https://github.com/user-attachments/files/17649520/debug.log)

2. For [polypatcher](https://github.com/Polyfrost/PolyPatcher) only, you cannot load game without deleting performance.MinecraftMixin_ToggleGLErrorChecking in mixins.patcher.json.
[crash-2024-11-07_00.55.01-client.txt](https://github.com/user-attachments/files/17649836/crash-2024-11-07_00.55.01-client.txt)
[debug.log](https://github.com/user-attachments/files/17649619/debug.log)

### Mod List

1. polysprint

2. polypatcher (without deleting mixin)

### MMC Instance Notes

I renamed action #759 to cleanroom-0.2.3-alpha-universal when testing!
not to confuse

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I have installed [Scalar 2.11.1](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by s0u7a** [comment]
Same issue

**Comment by kappa-maintainer** [comment]
Patching this is harder than I expected... 
Since the difficulty mainly come from its strange design, I decided to not fixing them before next Cleanroom release
Please make an issue in those mods repository instead

**Comment by kappa-maintainer** [comment]
The author of these mods is working on it
