### ISSUE TITLE
Crash with implib-1.1.5RC2

### ISSUE THREAD

**Issue by s0u7a** [CleanroomMC/Fugue#64]
### Your CleanroomMC Discord Username

s0u7a.net

### Cleanroom Version

0.2.3-alpha+build.36.run.771]

### Java Version

Java 22

### Graphics Card Vendor

Intel iGPU

### Bug Report

Log: https://mclo.gs/6ggw4rb
Debug log : https://mclo.gs/lizPLfh

### Mod List

Fugue 
Scalar
Implib

### MMC Instance Notes

This instance is built using Github Action.
Using installer artifact from commit: 3f4950f0184d43cf8abd4353f7243ed502d69976
Action URL: https://github.com/CleanroomMC/Cleanroom/actions/runs/11763515393

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I have installed [Scalar 2.11.1](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
`at roj.reflect.ReflectionUtils.<clinit>(ReflectionUtils.java:54)`
Classic "mod trying to invent another reflection wheel" scene

**Comment by kappa-maintainer** [comment]
Try to run with Java 21

**Comment by kappa-maintainer** [comment]
Tried to patch it, but the mod is simply too invasive
