### ISSUE TITLE
加入Modern-Warfare-Cubed-0.1-Dev-17崩溃

### ISSUE THREAD

**Issue by ralseilii** [CleanroomMC/Fugue#7]

**Comment by ralseilii** [comment]
mwc的前置是red core

**Comment by kappa-maintainer** [comment]
已联系作者

**Comment by Desoroxxx** [comment]
Could you try with this version: https://www.curseforge.com/minecraft/mc-mods/modern-warfare-cubed/files/5045949

**Comment by Desoroxxx** [comment]
Could you try with this version: https://www.curseforge.com/minecraft/mc-mods/modern-warfare-cubed/files/5046886

**Comment by kappa-maintainer** [comment]
24小时无回应视作已正常

**Comment by ralseilii** [comment]
新版本正常
