### ISSUE TITLE
Crash with Enchantments Control

### ISSUE THREAD

**Issue by jchung01** [CleanroomMC/Fugue#8]
Not sure which repo to report to, so reporting to this one as it looks like an ASM issue.

Cleanroom crashes with [Enchantments Control](https://www.curseforge.com/minecraft/mc-mods/enchantments-control), regardless of the setting of `"custom_localization"` in Ench Control's config.
Only mods added are Enchantments Control and Fugue, but crash is the same without Fugue.
[Crash report](https://mclo.gs/m0sqIjW), [latest.log](https://mclo.gs/LjZaFjX)
The [line](https://github.com/AustereTony-MCMods/Enchantments-Control/blob/1.12.2/src/main/java/austeretony/enchcontrol/common/config/ConfigLoader.java#L258) the crash report points to, and `localization` is initalized [here](https://github.com/AustereTony-MCMods/Enchantments-Control/blob/1.12.2/src/main/java/austeretony/enchcontrol/common/config/ConfigLoader.java#L206) which is called by ASM hook [here](https://github.com/AustereTony-MCMods/Enchantments-Control/blob/1.12.2/src/main/java/austeretony/enchcontrol/common/core/EnumInputClass.java#L97). If it's an issue with counting `INVOKESPECIAL`, the mod also counts `INVOKESPECIAL` in [this method](https://github.com/AustereTony-MCMods/Enchantments-Control/blob/1.12.2/src/main/java/austeretony/enchcontrol/common/core/EnumInputClass.java#L318) in case that should be fixed as well.

Using Cleanroom 15.24.0.3027.

**Comment by kappa-maintainer** [comment]
Fixed in Fugue 0.5.0
