### ISSUE TITLE
加入修复列表中的mod启动失败

### ISSUE THREAD

**Issue by Flukesuki** [CleanroomMC/Fugue#9]
植物魔法调整在fugue前缀加 ! 也启动失败，现在高级火箭也启动失败了
单独在一个cleanroom环境单加也会启动失败 删除了才能启动成功
https://mclo.gs/wad0c4n (植物魔法调整)
https://mclo.gs/3KpllVU (高级火箭)
是转换层更换的问题还是我的问题?

**Comment by kappa-maintainer** [comment]
Cleanroom更新了但是Fugue还没更新……别急
